# configs/pacman_config.yaml

# Environment settings
env:
  id: "ALE/MsPacman-v5"
  render_mode: "rgb_array"
  frame_stack: 3
  screen_size: 84

# Training Hyperparameters
training:
  num_envs: 4 ## should be the same as num_envs
  gamma: 0.99
  learning_rate: 0.0001
  n_steps: 5
  max_episodes: 500
  print_every: 10
  device: "cuda" # PyTorch uses 'cuda' for GPU


agent:
  _target_: "rl_project_new.agents.ACnetRLAgent"
  gamma: 0.99
  device: "cuda"
  # You can even nest the model inside!
  network:
    _target_: "rl_project_new.algorithms.ACnet.ActorCriticNetwork"
    hidden_dim: 256